// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package listing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SalesChannelServiceClient is the client API for SalesChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SalesChannelServiceClient interface {
	InitiateIngestion(ctx context.Context, in *InitiateIngestionRequest, opts ...grpc.CallOption) (*InitiateIngestionResponse, error)
}

type salesChannelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSalesChannelServiceClient(cc grpc.ClientConnInterface) SalesChannelServiceClient {
	return &salesChannelServiceClient{cc}
}

func (c *salesChannelServiceClient) InitiateIngestion(ctx context.Context, in *InitiateIngestionRequest, opts ...grpc.CallOption) (*InitiateIngestionResponse, error) {
	out := new(InitiateIngestionResponse)
	err := c.cc.Invoke(ctx, "/listing_api.SalesChannelService/InitiateIngestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SalesChannelServiceServer is the server API for SalesChannelService service.
// All implementations should embed UnimplementedSalesChannelServiceServer
// for forward compatibility
type SalesChannelServiceServer interface {
	InitiateIngestion(context.Context, *InitiateIngestionRequest) (*InitiateIngestionResponse, error)
}

// UnimplementedSalesChannelServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSalesChannelServiceServer struct {
}

func (UnimplementedSalesChannelServiceServer) InitiateIngestion(context.Context, *InitiateIngestionRequest) (*InitiateIngestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateIngestion not implemented")
}

// UnsafeSalesChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SalesChannelServiceServer will
// result in compilation errors.
type UnsafeSalesChannelServiceServer interface {
	mustEmbedUnimplementedSalesChannelServiceServer()
}

func RegisterSalesChannelServiceServer(s grpc.ServiceRegistrar, srv SalesChannelServiceServer) {
	s.RegisterService(&SalesChannelService_ServiceDesc, srv)
}

func _SalesChannelService_InitiateIngestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateIngestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesChannelServiceServer).InitiateIngestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/listing_api.SalesChannelService/InitiateIngestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesChannelServiceServer).InitiateIngestion(ctx, req.(*InitiateIngestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SalesChannelService_ServiceDesc is the grpc.ServiceDesc for SalesChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SalesChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "listing_api.SalesChannelService",
	HandlerType: (*SalesChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateIngestion",
			Handler:    _SalesChannelService_InitiateIngestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/listing/sales_channel_service.proto",
}
